### ISSUE TITLE
权限问题

### ISSUE THREAD

**Issue by CwjXFH** [silenceshell/topic#4]
以root身份进入容器，下载topic后执行该命令，没有权限，top命令则可以正常执行：
![image](https://user-images.githubusercontent.com/11468733/134447196-e1bbcc58-94a1-4d1f-bdec-9848fe6b8898.png)

**Comment by silenceshell** [comment]
看下这个文件的权限是否有 r 
```
# ls -l /proc/1/io
-r-------- 1 root root 0 Sep 23 02:41 io
```

**Comment by CwjXFH** [comment]
需要使用/proc/1/io文件所属用户进入容器才可以
